org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.2
fabric_loader_version=0.19.3
fabric_api_version=0.156.0+26.2
loom_version=1.17.19

# Stable Fabric 26.2 runtime matrix. Version IDs are immutable Modrinth coordinates.
sodium_version_id=2Yom1N68
iris_version_id=oaD6KQls
viafabricplus_version_id=NVFW4VRx
sodium_sha512=627fbf9625a4b94693c789c84a0686ffe558c0b1ecbeccf2602a903caafa9e126548b644282aa9c391dc798930d378724a383bea6b4397c5294d59ba5c0a6936
iris_sha512=c1b46bcd1a0068deab3ae364a7229d31e27b7d45aea960e47503b8514354426badf83f354529db35d83e6b55727a53895fb9f13085e51d8148ee6765affac924
viafabricplus_sha512=41add6788f1df8b64f1c606f71e8ebeef2e4435a2a85c026eee5bfcaf6fc0f4ee28a30a4481e757a88007c62b32b8e8aec0d968dede0a51be95e72f6ddaa85e8

mod_version=1.2+mc26.2
maven_group=io.github.openzen
archives_base_name=mizulune-fabric
