<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Mizulune.FantnelHost</AssemblyName>
    <RootNamespace>Mizulune.FantnelHost</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\fantnel\Nirvana.Public\Nirvana.Public.csproj" />
  </ItemGroup>
</Project>
